language: rust
cache: cargo
dist: focal

os:
  - linux

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - sqlite3

env:
  global:
    - RUSTFLAGS="-C link-dead-code"

stage: build and test
script: cargo build --verbose

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - stage: static analysis
      name: "Clippy"
      addons: { }
      rust: stable
      before_script:
        - rustup component add clippy
        - cargo clean -p cargo-docset
      script: cargo clippy -- -D clippy::all

stages:
  - build and test
  - static analysis
